# Generated by Django 5.0.1 on 2024-02-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='field2',
            field=models.TextField(default='asdfads'),
            preserve_default=False,
        ),
    ]
