# Generated by Django 5.0.1 on 2024-02-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_recipe_field2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='field2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
