# Generated by Django 5.0.1 on 2024-03-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_recipereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='field2',
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
