# Generated by Django 5.0.1 on 2024-03-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_recipe_field2_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
