# Generated by Django 5.0.1 on 2024-03-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_recipe_title_az_recipe_title_en_us_recipe_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
